import awalMusimImage from "../../assets/WhatsApp Image 2026-05-09 at 09.29.33.jpeg";
import plusThaifSeptemberImage from "../../assets/WhatsApp Image 2026-06-06 at 23.43.35.jpeg";
import plusThaifDesemberImage from "../../assets/WhatsApp Image 2026-06-07 at 14.19.41.jpeg";
import plusThaifPremiumImage from "../../assets/WhatsApp Image 2026-06-07 at 14.19.42.jpeg";
import sekamarBer4Image from "../../assets/WhatsApp Image 2026-06-10 at 17.50.14.jpeg";
import liburanDesemberImage from "../../assets/WhatsApp Image 2026-06-15 at 10.38.50.jpeg";
import liburanJanuariImage from "../../assets/WhatsApp Image 2026-06-15 at 10.52.37.jpeg";
import liburanJanuari2027Image from "../../assets/WhatsApp Image 2026-06-15 at 10.57.25.jpeg";
import syawal2027Image from "../../assets/WhatsApp Image 2026-06-15 at 22.07.09.jpeg";

export const packageCards = [
  {
    id: "plus-thaif-september",
    title: "Paket Umroh Plus Thaif",
    date: "21 September 2026",
    duration: "12 Hari",
    departure: "September 2026",
    category: "Plus Thaif",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Qatar Airways / Oman Air / Etihad",
    hotelMakkah: "Jada Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: true,
    seats: 20,
    tags: ["City Tour Thaif", "Visa", "Makan 3x", "Air Zam-Zam 5L"],
    price: "Rp 25.000.000",
    image: plusThaifSeptemberImage,
    badge: "Promo",
    sold: false,
    description:
      "Program umroh plus Thaif dengan city tour, hotel strategis, dan pilihan maskapai premium untuk perjalanan ibadah yang nyaman.",
    includes: [
      "Tiket ekonomi PP",
      "Visa umroh resmi",
      "Makan 3 kali sehari",
      "City tour Makkah dan Madinah",
      "City tour Thaif",
      "Transportasi terbaik, air zam-zam 5 liter, dan handling JKT & Saudi",
    ],
  },
  {
    id: "awal-musim",
    title: "Paket Umroh Awal Musim",
    date: "28 Juni 2026",
    duration: "9 Hari",
    departure: "Juni 2026",
    category: "Awal Musim",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Etihad / Oman Air",
    hotelMakkah: "Waha Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: true,
    seats: 0,
    tags: ["Visa", "Manasik", "Airport Handling", "Air Zam-Zam 5L"],
    price: "Rp 26.000.000",
    image: awalMusimImage,
    badge: "Promo",
    sold: true,
    description:
      "Paket umroh awal musim dengan suasana lebih nyaman, pembimbing berpengalaman, dan fasilitas lengkap sesuai brosur.",
    includes: [
      "Tiket pesawat PP",
      "Perlengkapan umroh lengkap",
      "Manasik dan bimbingan ibadah",
      "Airport handling",
      "Visa umroh resmi",
      "Konsumsi 3 kali sehari, city tour Mekkah-Madinah, dan air zam-zam 5 liter",
    ],
  },
  {
    id: "plus-thaif-desember",
    title: "Paket Umroh Plus Thaif Desember",
    date: "18 Desember 2026",
    duration: "12 Hari",
    departure: "Desember 2026",
    category: "Plus Thaif",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Saudia",
    hotelMakkah: "Jada Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: false,
    seats: 18,
    tags: ["Plus Thaif", "Saudia", "Makan 3x", "Air Zam-Zam 5L"],
    price: "Rp 29.000.000",
    image: plusThaifDesemberImage,
    sold: false,
    description:
      "Program umroh plus Thaif keberangkatan Desember dengan maskapai Saudia dan akomodasi strategis sesuai brosur.",
    includes: [
      "Tiket ekonomi PP",
      "Visa umroh resmi",
      "Makan 3 kali sehari",
      "City tour Makkah dan Madinah",
      "City tour Thaif",
      "Transportasi terbaik, air zam-zam 5 liter, dan handling JKT & Saudi",
    ],
  },
  {
    id: "plus-thaif-premium",
    title: "Paket Umroh Plus Thaif Premium",
    date: "Sesuai jadwal brosur",
    duration: "9 Hari",
    departure: "Desember 2026",
    category: "Plus Thaif Premium",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Qatar Airways / Oman Air / Etihad",
    hotelMakkah: "Jada Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: true,
    seats: 16,
    tags: ["Premium", "Plus Thaif", "Visa", "Maskapai Pilihan"],
    price: "Rp 26.000.000",
    image: plusThaifPremiumImage,
    badge: "Promo",
    sold: false,
    description:
      "Varian paket plus Thaif dengan pilihan maskapai premium dan hotel strategis untuk jamaah yang ingin perjalanan lebih fleksibel.",
    includes: [
      "Tiket ekonomi PP",
      "Visa umroh resmi",
      "Makan 3 kali sehari",
      "City tour Makkah dan Madinah",
      "City tour Thaif",
      "Transportasi terbaik, air zam-zam 5 liter, dan handling JKT & Saudi",
    ],
  },
  {
    id: "sekamar-ber4",
    title: "Paket Umroh Plus Thaif Sekamar Ber 4",
    date: "15 November 2026",
    duration: "9 Hari",
    departure: "November 2026",
    category: "Plus Thaif Sekamar Ber 4",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Saudia",
    hotelMakkah: "Waha Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: false,
    seats: 14,
    tags: ["Plus Thaif", "Visa", "Makan 3x", "Sekamar Ber 4"],
    price: "Rp 28.500.000",
    image: sekamarBer4Image,
    sold: false,
    description:
      "Paket umroh plus Thaif dengan skema sekamar berempat, maskapai Saudia, dan fasilitas lengkap sesuai brosur November 2026.",
    includes: [
      "Tiket ekonomi PP",
      "Visa umroh resmi",
      "Makan 3 kali sehari",
      "City tour Makkah dan Madinah",
      "City tour Thaif",
      "Transportasi terbaik, air zam-zam 5 liter, dan handling JKT & Saudi",
    ],
  },
  {
    id: "liburan-desember",
    title: "Paket Umroh Liburan Desember",
    date: "19 Desember 2026",
    duration: "9 Hari",
    departure: "Desember 2026",
    category: "Liburan Desember",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Saudia",
    hotelMakkah: "Jada Ajyad / Setaraf",
    hotelMadinah: "Mukhtar Al Gharbi / Setaraf",
    promo: false,
    seats: 24,
    tags: ["Liburan", "City Tour", "Saudia", "Family Friendly"],
    price: "Mulai Rp 29.000.000",
    image: liburanDesemberImage,
    sold: false,
    description:
      "Paket musim liburan Desember dengan pilihan quad, triple, dan double, cocok untuk keluarga maupun rombongan.",
    includes: [
      "Visa umroh resmi",
      "Hotel Makkah dan Madinah",
      "Free city tour",
      "Pendamping ibadah",
      "Maskapai Saudia",
      "Layanan amanah dan profesional",
    ],
  },
  {
    id: "liburan-januari-2026",
    title: "Paket Umroh Liburan Januari 2026",
    date: "16 Januari 2026",
    duration: "9 Hari",
    departure: "Januari 2026",
    category: "Liburan Januari",
    airport: "Soekarno-Hatta (CGK)",
    airline: "IndiGo",
    hotelMakkah: "Fajr Badie 4 / Badr Almassa",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: false,
    seats: 12,
    tags: ["Liburan", "IndiGo", "City Tour", "Quad/Triple/Double"],
    price: "Mulai Rp 24.900.000",
    image: liburanJanuariImage,
    sold: false,
    description:
      "Paket liburan Januari dengan pilihan kamar quad, triple, dan double serta free city tour Makkah dan Madinah.",
    includes: [
      "Visa umroh resmi",
      "Hotel Makkah dan Madinah",
      "Free city tour",
      "Pendamping ibadah",
      "Maskapai IndiGo",
      "Layanan amanah dan profesional",
    ],
  },
  {
    id: "liburan-januari-2027",
    title: "Paket Umroh Liburan Januari 2027",
    date: "16 Januari 2027",
    duration: "9 Hari",
    departure: "Januari 2027",
    category: "Liburan Januari",
    airport: "Soekarno-Hatta (CGK)",
    airline: "IndiGo",
    hotelMakkah: "Fajr Badie 4 / Badr Almassa",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: true,
    seats: 22,
    tags: ["Liburan", "IndiGo", "City Tour", "Promo Tahun Baru"],
    price: "Mulai Rp 24.900.000",
    image: liburanJanuari2027Image,
    badge: "Promo",
    sold: false,
    description:
      "Paket awal tahun 2027 dengan city tour, hotel strategis, dan pilihan kamar fleksibel untuk keluarga maupun rombongan.",
    includes: [
      "Visa umroh resmi",
      "Hotel Makkah dan Madinah",
      "Free city tour",
      "Pendamping ibadah",
      "Maskapai IndiGo",
      "Layanan amanah dan profesional",
    ],
  },
  {
    id: "syawal-2027",
    title: "Paket Umroh Syawal 2027",
    date: "15 Maret 2027",
    duration: "9 Hari",
    departure: "Maret 2027",
    category: "Syawal 2027",
    airport: "Soekarno-Hatta (CGK)",
    airline: "Qatar Airways",
    hotelMakkah: "Waha Ajyad",
    hotelMadinah: "Mukhtar Al Gharbi",
    promo: true,
    seats: 30,
    tags: ["Syawal", "Qatar Airways", "Makan 3x", "Air Zam-Zam 5L"],
    price: "Mulai Rp 26.500.000",
    image: syawal2027Image,
    badge: "Promo",
    sold: false,
    description:
      "Paket umroh Syawal dengan harga bertingkat untuk quad, triple, dan double serta hotel strategis dekat area ibadah.",
    includes: [
      "Tiket PP Qatar Airways",
      "Visa umroh resmi",
      "Hotel Makkah dan Madinah",
      "Makan 3 kali sehari",
      "City tour Makkah dan Madinah",
      "Handling bandara, manasik, dan muthawif berpengalaman",
    ],
  },
];

export function findPackageById(id) {
  return packageCards.find((item) => item.id === id);
}
